// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: proto/admin/v1/admin.proto

package adminv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolicyAdmin_CreatePolicy_FullMethodName = "/admin.v1.PolicyAdmin/CreatePolicy"
	PolicyAdmin_DeletePolicy_FullMethodName = "/admin.v1.PolicyAdmin/DeletePolicy"
	PolicyAdmin_ListPolicies_FullMethodName = "/admin.v1.PolicyAdmin/ListPolicies"
	PolicyAdmin_ReloadPolicy_FullMethodName = "/admin.v1.PolicyAdmin/ReloadPolicy"
)

// PolicyAdminClient is the client API for PolicyAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PolicyAdmin manages exchange policies at runtime.
// Changes take effect immediately and persist across server restarts.
// This service must be network-restricted — it should not be reachable
// from workloads that consume the TokenExchange API.
type PolicyAdminClient interface {
	// CreatePolicy adds a new exchange policy.
	// Returns ALREADY_EXISTS if the policy name or (subject, target) pair
	// conflicts with an existing YAML or dynamic policy.
	CreatePolicy(ctx context.Context, in *CreatePolicyRequest, opts ...grpc.CallOption) (*CreatePolicyResponse, error)
	// DeletePolicy removes a dynamic policy by name.
	// Returns NOT_FOUND if the policy does not exist in the dynamic store.
	// Returns FAILED_PRECONDITION if the policy was loaded from the YAML file
	// (YAML policies can only be removed by editing the file and calling ReloadPolicy or sending SIGHUP).
	DeletePolicy(ctx context.Context, in *DeletePolicyRequest, opts ...grpc.CallOption) (*DeletePolicyResponse, error)
	// ListPolicies returns all active policies — both YAML-sourced and dynamic.
	// Each entry includes a source field ("yaml" or "dynamic") so callers can
	// distinguish policies that originated from the file versus the API.
	ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesResponse, error)
	// ReloadPolicy re-reads the YAML policy file from disk and merges it with
	// all dynamic policies, exactly as SIGHUP does. Use this instead of sending
	// a signal in production environments. If the file is invalid the active
	// policy is unchanged and an error is returned.
	ReloadPolicy(ctx context.Context, in *ReloadPolicyRequest, opts ...grpc.CallOption) (*ReloadPolicyResponse, error)
}

type policyAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyAdminClient(cc grpc.ClientConnInterface) PolicyAdminClient {
	return &policyAdminClient{cc}
}

func (c *policyAdminClient) CreatePolicy(ctx context.Context, in *CreatePolicyRequest, opts ...grpc.CallOption) (*CreatePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePolicyResponse)
	err := c.cc.Invoke(ctx, PolicyAdmin_CreatePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyAdminClient) DeletePolicy(ctx context.Context, in *DeletePolicyRequest, opts ...grpc.CallOption) (*DeletePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePolicyResponse)
	err := c.cc.Invoke(ctx, PolicyAdmin_DeletePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyAdminClient) ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPoliciesResponse)
	err := c.cc.Invoke(ctx, PolicyAdmin_ListPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyAdminClient) ReloadPolicy(ctx context.Context, in *ReloadPolicyRequest, opts ...grpc.CallOption) (*ReloadPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadPolicyResponse)
	err := c.cc.Invoke(ctx, PolicyAdmin_ReloadPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyAdminServer is the server API for PolicyAdmin service.
// All implementations must embed UnimplementedPolicyAdminServer
// for forward compatibility.
//
// PolicyAdmin manages exchange policies at runtime.
// Changes take effect immediately and persist across server restarts.
// This service must be network-restricted — it should not be reachable
// from workloads that consume the TokenExchange API.
type PolicyAdminServer interface {
	// CreatePolicy adds a new exchange policy.
	// Returns ALREADY_EXISTS if the policy name or (subject, target) pair
	// conflicts with an existing YAML or dynamic policy.
	CreatePolicy(context.Context, *CreatePolicyRequest) (*CreatePolicyResponse, error)
	// DeletePolicy removes a dynamic policy by name.
	// Returns NOT_FOUND if the policy does not exist in the dynamic store.
	// Returns FAILED_PRECONDITION if the policy was loaded from the YAML file
	// (YAML policies can only be removed by editing the file and calling ReloadPolicy or sending SIGHUP).
	DeletePolicy(context.Context, *DeletePolicyRequest) (*DeletePolicyResponse, error)
	// ListPolicies returns all active policies — both YAML-sourced and dynamic.
	// Each entry includes a source field ("yaml" or "dynamic") so callers can
	// distinguish policies that originated from the file versus the API.
	ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesResponse, error)
	// ReloadPolicy re-reads the YAML policy file from disk and merges it with
	// all dynamic policies, exactly as SIGHUP does. Use this instead of sending
	// a signal in production environments. If the file is invalid the active
	// policy is unchanged and an error is returned.
	ReloadPolicy(context.Context, *ReloadPolicyRequest) (*ReloadPolicyResponse, error)
	mustEmbedUnimplementedPolicyAdminServer()
}

// UnimplementedPolicyAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyAdminServer struct{}

func (UnimplementedPolicyAdminServer) CreatePolicy(context.Context, *CreatePolicyRequest) (*CreatePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePolicy not implemented")
}
func (UnimplementedPolicyAdminServer) DeletePolicy(context.Context, *DeletePolicyRequest) (*DeletePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePolicy not implemented")
}
func (UnimplementedPolicyAdminServer) ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPolicies not implemented")
}
func (UnimplementedPolicyAdminServer) ReloadPolicy(context.Context, *ReloadPolicyRequest) (*ReloadPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadPolicy not implemented")
}
func (UnimplementedPolicyAdminServer) mustEmbedUnimplementedPolicyAdminServer() {}
func (UnimplementedPolicyAdminServer) testEmbeddedByValue()                     {}

// UnsafePolicyAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyAdminServer will
// result in compilation errors.
type UnsafePolicyAdminServer interface {
	mustEmbedUnimplementedPolicyAdminServer()
}

func RegisterPolicyAdminServer(s grpc.ServiceRegistrar, srv PolicyAdminServer) {
	// If the following call panics, it indicates UnimplementedPolicyAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyAdmin_ServiceDesc, srv)
}

func _PolicyAdmin_CreatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyAdminServer).CreatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyAdmin_CreatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyAdminServer).CreatePolicy(ctx, req.(*CreatePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyAdmin_DeletePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyAdminServer).DeletePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyAdmin_DeletePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyAdminServer).DeletePolicy(ctx, req.(*DeletePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyAdmin_ListPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyAdminServer).ListPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyAdmin_ListPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyAdminServer).ListPolicies(ctx, req.(*ListPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyAdmin_ReloadPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyAdminServer).ReloadPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyAdmin_ReloadPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyAdminServer).ReloadPolicy(ctx, req.(*ReloadPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyAdmin_ServiceDesc is the grpc.ServiceDesc for PolicyAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.v1.PolicyAdmin",
	HandlerType: (*PolicyAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePolicy",
			Handler:    _PolicyAdmin_CreatePolicy_Handler,
		},
		{
			MethodName: "DeletePolicy",
			Handler:    _PolicyAdmin_DeletePolicy_Handler,
		},
		{
			MethodName: "ListPolicies",
			Handler:    _PolicyAdmin_ListPolicies_Handler,
		},
		{
			MethodName: "ReloadPolicy",
			Handler:    _PolicyAdmin_ReloadPolicy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/admin/v1/admin.proto",
}
