// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/admin/v1/admin.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PolicyRule mirrors the YAML policy structure.
type PolicyRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the unique human-readable identifier used in audit logs.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// subject is the SPIFFE ID of the calling service.
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// target is the SPIFFE ID of the target service.
	Target string `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	// allowed_scopes is the complete set of scopes this subject may request.
	AllowedScopes []string `protobuf:"bytes,4,rep,name=allowed_scopes,json=allowedScopes,proto3" json:"allowed_scopes,omitempty"`
	// max_ttl is the maximum token lifetime in seconds.
	MaxTtl        int32 `protobuf:"varint,5,opt,name=max_ttl,json=maxTtl,proto3" json:"max_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRule) Reset() {
	*x = PolicyRule{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRule) ProtoMessage() {}

func (x *PolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRule.ProtoReflect.Descriptor instead.
func (*PolicyRule) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PolicyRule) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PolicyRule) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *PolicyRule) GetAllowedScopes() []string {
	if x != nil {
		return x.AllowedScopes
	}
	return nil
}

func (x *PolicyRule) GetMaxTtl() int32 {
	if x != nil {
		return x.MaxTtl
	}
	return 0
}

type CreatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *PolicyRule            `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePolicyRequest) Reset() {
	*x = CreatePolicyRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolicyRequest) ProtoMessage() {}

func (x *CreatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolicyRequest.ProtoReflect.Descriptor instead.
func (*CreatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePolicyRequest) GetRule() *PolicyRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type CreatePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *PolicyRule            `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePolicyResponse) Reset() {
	*x = CreatePolicyResponse{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolicyResponse) ProtoMessage() {}

func (x *CreatePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolicyResponse.ProtoReflect.Descriptor instead.
func (*CreatePolicyResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePolicyResponse) GetRule() *PolicyRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type DeletePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyRequest) Reset() {
	*x = DeletePolicyRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyRequest) ProtoMessage() {}

func (x *DeletePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyRequest.ProtoReflect.Descriptor instead.
func (*DeletePolicyRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *DeletePolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeletePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyResponse) Reset() {
	*x = DeletePolicyResponse{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyResponse) ProtoMessage() {}

func (x *DeletePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyResponse.ProtoReflect.Descriptor instead.
func (*DeletePolicyResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

type ListPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesRequest) Reset() {
	*x = ListPoliciesRequest{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesRequest) ProtoMessage() {}

func (x *ListPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

// PolicyEntry wraps a rule with its origin.
type PolicyEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Rule  *PolicyRule            `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	// source is either "yaml" or "dynamic".
	Source        string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyEntry) Reset() {
	*x = PolicyEntry{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyEntry) ProtoMessage() {}

func (x *PolicyEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyEntry.ProtoReflect.Descriptor instead.
func (*PolicyEntry) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *PolicyEntry) GetRule() *PolicyRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *PolicyEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ListPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*PolicyEntry         `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesResponse) Reset() {
	*x = ListPoliciesResponse{}
	mi := &file_proto_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesResponse) ProtoMessage() {}

func (x *ListPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ListPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ListPoliciesResponse) GetPolicies() []*PolicyEntry {
	if x != nil {
		return x.Policies
	}
	return nil
}

var File_proto_admin_v1_admin_proto protoreflect.FileDescriptor

const file_proto_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/admin/v1/admin.proto\x12\badmin.v1\"\x92\x01\n" +
	"\n" +
	"PolicyRule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12%\n" +
	"\x0eallowed_scopes\x18\x04 \x03(\tR\rallowedScopes\x12\x17\n" +
	"\amax_ttl\x18\x05 \x01(\x05R\x06maxTtl\"?\n" +
	"\x13CreatePolicyRequest\x12(\n" +
	"\x04rule\x18\x01 \x01(\v2\x14.admin.v1.PolicyRuleR\x04rule\"@\n" +
	"\x14CreatePolicyResponse\x12(\n" +
	"\x04rule\x18\x01 \x01(\v2\x14.admin.v1.PolicyRuleR\x04rule\")\n" +
	"\x13DeletePolicyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14DeletePolicyResponse\"\x15\n" +
	"\x13ListPoliciesRequest\"O\n" +
	"\vPolicyEntry\x12(\n" +
	"\x04rule\x18\x01 \x01(\v2\x14.admin.v1.PolicyRuleR\x04rule\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\"I\n" +
	"\x14ListPoliciesResponse\x121\n" +
	"\bpolicies\x18\x01 \x03(\v2\x15.admin.v1.PolicyEntryR\bpolicies2\xfa\x01\n" +
	"\vPolicyAdmin\x12M\n" +
	"\fCreatePolicy\x12\x1d.admin.v1.CreatePolicyRequest\x1a\x1e.admin.v1.CreatePolicyResponse\x12M\n" +
	"\fDeletePolicy\x12\x1d.admin.v1.DeletePolicyRequest\x1a\x1e.admin.v1.DeletePolicyResponse\x12M\n" +
	"\fListPolicies\x12\x1d.admin.v1.ListPoliciesRequest\x1a\x1e.admin.v1.ListPoliciesResponseB<Z:github.com/ngaddam369/svid-exchange/proto/admin/v1;adminv1b\x06proto3"

var (
	file_proto_admin_v1_admin_proto_rawDescOnce sync.Once
	file_proto_admin_v1_admin_proto_rawDescData []byte
)

func file_proto_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_proto_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_proto_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_v1_admin_proto_rawDesc), len(file_proto_admin_v1_admin_proto_rawDesc)))
	})
	return file_proto_admin_v1_admin_proto_rawDescData
}

var file_proto_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_admin_v1_admin_proto_goTypes = []any{
	(*PolicyRule)(nil),           // 0: admin.v1.PolicyRule
	(*CreatePolicyRequest)(nil),  // 1: admin.v1.CreatePolicyRequest
	(*CreatePolicyResponse)(nil), // 2: admin.v1.CreatePolicyResponse
	(*DeletePolicyRequest)(nil),  // 3: admin.v1.DeletePolicyRequest
	(*DeletePolicyResponse)(nil), // 4: admin.v1.DeletePolicyResponse
	(*ListPoliciesRequest)(nil),  // 5: admin.v1.ListPoliciesRequest
	(*PolicyEntry)(nil),          // 6: admin.v1.PolicyEntry
	(*ListPoliciesResponse)(nil), // 7: admin.v1.ListPoliciesResponse
}
var file_proto_admin_v1_admin_proto_depIdxs = []int32{
	0, // 0: admin.v1.CreatePolicyRequest.rule:type_name -> admin.v1.PolicyRule
	0, // 1: admin.v1.CreatePolicyResponse.rule:type_name -> admin.v1.PolicyRule
	0, // 2: admin.v1.PolicyEntry.rule:type_name -> admin.v1.PolicyRule
	6, // 3: admin.v1.ListPoliciesResponse.policies:type_name -> admin.v1.PolicyEntry
	1, // 4: admin.v1.PolicyAdmin.CreatePolicy:input_type -> admin.v1.CreatePolicyRequest
	3, // 5: admin.v1.PolicyAdmin.DeletePolicy:input_type -> admin.v1.DeletePolicyRequest
	5, // 6: admin.v1.PolicyAdmin.ListPolicies:input_type -> admin.v1.ListPoliciesRequest
	2, // 7: admin.v1.PolicyAdmin.CreatePolicy:output_type -> admin.v1.CreatePolicyResponse
	4, // 8: admin.v1.PolicyAdmin.DeletePolicy:output_type -> admin.v1.DeletePolicyResponse
	7, // 9: admin.v1.PolicyAdmin.ListPolicies:output_type -> admin.v1.ListPoliciesResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_admin_v1_admin_proto_init() }
func file_proto_admin_v1_admin_proto_init() {
	if File_proto_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_v1_admin_proto_rawDesc), len(file_proto_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_proto_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_proto_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_proto_admin_v1_admin_proto = out.File
	file_proto_admin_v1_admin_proto_goTypes = nil
	file_proto_admin_v1_admin_proto_depIdxs = nil
}
