// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: proto/exchange/v1/exchange.proto

package exchangev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TokenExchange_Exchange_FullMethodName = "/exchange.v1.TokenExchange/Exchange"
)

// TokenExchangeClient is the client API for TokenExchange service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TokenExchange exchanges a caller's SPIFFE SVID (presented via mTLS) for a
// scoped short-lived JWT targeting a specific service.
type TokenExchangeClient interface {
	Exchange(ctx context.Context, in *ExchangeRequest, opts ...grpc.CallOption) (*ExchangeResponse, error)
}

type tokenExchangeClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenExchangeClient(cc grpc.ClientConnInterface) TokenExchangeClient {
	return &tokenExchangeClient{cc}
}

func (c *tokenExchangeClient) Exchange(ctx context.Context, in *ExchangeRequest, opts ...grpc.CallOption) (*ExchangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeResponse)
	err := c.cc.Invoke(ctx, TokenExchange_Exchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenExchangeServer is the server API for TokenExchange service.
// All implementations must embed UnimplementedTokenExchangeServer
// for forward compatibility.
//
// TokenExchange exchanges a caller's SPIFFE SVID (presented via mTLS) for a
// scoped short-lived JWT targeting a specific service.
type TokenExchangeServer interface {
	Exchange(context.Context, *ExchangeRequest) (*ExchangeResponse, error)
	mustEmbedUnimplementedTokenExchangeServer()
}

// UnimplementedTokenExchangeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenExchangeServer struct{}

func (UnimplementedTokenExchangeServer) Exchange(context.Context, *ExchangeRequest) (*ExchangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exchange not implemented")
}
func (UnimplementedTokenExchangeServer) mustEmbedUnimplementedTokenExchangeServer() {}
func (UnimplementedTokenExchangeServer) testEmbeddedByValue()                       {}

// UnsafeTokenExchangeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenExchangeServer will
// result in compilation errors.
type UnsafeTokenExchangeServer interface {
	mustEmbedUnimplementedTokenExchangeServer()
}

func RegisterTokenExchangeServer(s grpc.ServiceRegistrar, srv TokenExchangeServer) {
	// If the following call panics, it indicates UnimplementedTokenExchangeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokenExchange_ServiceDesc, srv)
}

func _TokenExchange_Exchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenExchangeServer).Exchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenExchange_Exchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenExchangeServer).Exchange(ctx, req.(*ExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenExchange_ServiceDesc is the grpc.ServiceDesc for TokenExchange service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenExchange_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exchange.v1.TokenExchange",
	HandlerType: (*TokenExchangeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exchange",
			Handler:    _TokenExchange_Exchange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/exchange/v1/exchange.proto",
}
