// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/exchange/v1/exchange.proto

package exchangev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExchangeRequest carries what the caller wants — NOT who the caller is.
// The caller's identity is extracted from the mTLS peer certificate and cannot
// be forged via the request body.
type ExchangeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target_service is the SPIFFE ID of the service being called.
	TargetService string `protobuf:"bytes,1,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`
	// scopes are the permission scopes requested for this token.
	Scopes []string `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// ttl_seconds is the requested TTL; capped by the policy max_ttl.
	TtlSeconds    int32 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRequest) Reset() {
	*x = ExchangeRequest{}
	mi := &file_proto_exchange_v1_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRequest) ProtoMessage() {}

func (x *ExchangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exchange_v1_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRequest.ProtoReflect.Descriptor instead.
func (*ExchangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_exchange_v1_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *ExchangeRequest) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *ExchangeRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ExchangeRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type ExchangeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token is the signed ES256 JWT.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// expires_at is the unix timestamp when the token expires.
	ExpiresAt int64 `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// granted_scopes are the scopes actually granted (subset of requested).
	GrantedScopes []string `protobuf:"bytes,3,rep,name=granted_scopes,json=grantedScopes,proto3" json:"granted_scopes,omitempty"`
	// token_id is the JWT jti claim — tracked for future replay protection.
	TokenId       string `protobuf:"bytes,4,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeResponse) Reset() {
	*x = ExchangeResponse{}
	mi := &file_proto_exchange_v1_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeResponse) ProtoMessage() {}

func (x *ExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exchange_v1_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeResponse.ProtoReflect.Descriptor instead.
func (*ExchangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_exchange_v1_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangeResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ExchangeResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *ExchangeResponse) GetGrantedScopes() []string {
	if x != nil {
		return x.GrantedScopes
	}
	return nil
}

func (x *ExchangeResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

var File_proto_exchange_v1_exchange_proto protoreflect.FileDescriptor

const file_proto_exchange_v1_exchange_proto_rawDesc = "" +
	"\n" +
	" proto/exchange/v1/exchange.proto\x12\vexchange.v1\"q\n" +
	"\x0fExchangeRequest\x12%\n" +
	"\x0etarget_service\x18\x01 \x01(\tR\rtargetService\x12\x16\n" +
	"\x06scopes\x18\x02 \x03(\tR\x06scopes\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x05R\n" +
	"ttlSeconds\"\x89\x01\n" +
	"\x10ExchangeResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\x12%\n" +
	"\x0egranted_scopes\x18\x03 \x03(\tR\rgrantedScopes\x12\x19\n" +
	"\btoken_id\x18\x04 \x01(\tR\atokenId2X\n" +
	"\rTokenExchange\x12G\n" +
	"\bExchange\x12\x1c.exchange.v1.ExchangeRequest\x1a\x1d.exchange.v1.ExchangeResponseBBZ@github.com/ngaddam369/svid-exchange/proto/exchange/v1;exchangev1b\x06proto3"

var (
	file_proto_exchange_v1_exchange_proto_rawDescOnce sync.Once
	file_proto_exchange_v1_exchange_proto_rawDescData []byte
)

func file_proto_exchange_v1_exchange_proto_rawDescGZIP() []byte {
	file_proto_exchange_v1_exchange_proto_rawDescOnce.Do(func() {
		file_proto_exchange_v1_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_exchange_v1_exchange_proto_rawDesc), len(file_proto_exchange_v1_exchange_proto_rawDesc)))
	})
	return file_proto_exchange_v1_exchange_proto_rawDescData
}

var file_proto_exchange_v1_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_exchange_v1_exchange_proto_goTypes = []any{
	(*ExchangeRequest)(nil),  // 0: exchange.v1.ExchangeRequest
	(*ExchangeResponse)(nil), // 1: exchange.v1.ExchangeResponse
}
var file_proto_exchange_v1_exchange_proto_depIdxs = []int32{
	0, // 0: exchange.v1.TokenExchange.Exchange:input_type -> exchange.v1.ExchangeRequest
	1, // 1: exchange.v1.TokenExchange.Exchange:output_type -> exchange.v1.ExchangeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_exchange_v1_exchange_proto_init() }
func file_proto_exchange_v1_exchange_proto_init() {
	if File_proto_exchange_v1_exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_exchange_v1_exchange_proto_rawDesc), len(file_proto_exchange_v1_exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_exchange_v1_exchange_proto_goTypes,
		DependencyIndexes: file_proto_exchange_v1_exchange_proto_depIdxs,
		MessageInfos:      file_proto_exchange_v1_exchange_proto_msgTypes,
	}.Build()
	File_proto_exchange_v1_exchange_proto = out.File
	file_proto_exchange_v1_exchange_proto_goTypes = nil
	file_proto_exchange_v1_exchange_proto_depIdxs = nil
}
